### ISSUE TITLE
Trying to use crunch with Polkadex substrate chain fails with Invalid Metadata error

### ISSUE THREAD

**Issue by radiumb** [turboflakes/crunch#5]
Hi,

We are trying to use crunch (latest crunch version, built from source, tried the binary too) with Polkadex chain and it fails with following error:

$ crunch --config-path /home/user/.env.pdex --substrate-ws-url ws://127.0.0.1:9945/ view
[2022-02-11T12:31:56Z INFO crunch] crunch v0.4.1 * Crunch is a command-line interface (CLI) to claim staking rewards (flakes) every X hours for Substrate-based chains
[2022-02-11T12:31:56Z ERROR crunch::crunch] Invalid Metadata: Invalid version
[2022-02-11T12:31:56Z INFO crunch::crunch] Awaiting for connection using ws://127.0.0.1:9945/

--------------
We also tried to save polkadex metadata using subxt to metadata/polkadex_metadata.scale and compiled crunch again, but no go. Attaching polkadex_metadata.scale
[polkadex_metadata.txt](https://github.com/turboflakes/crunch/files/8068488/polkadex_metadata.txt)

We are currently using crunch successfully for kusama chain. Any help is appreciated.

**Comment by paulormart** [comment]
Hi @radiumb glad you posted your issue here.

Apart from the `polkadex_metadata.scale`, a polkadex specific module to load the metadata file is also needed. Have a look at the kusama module [here](https://github.com/turboflakes/crunch/blob/main/src/runtimes/kusama.rs). 

If polkadex staking pallet uses the same events and storage methods as the ones in the relay chain, you can just copy the kusama module [here](https://github.com/turboflakes/crunch/blob/main/src/runtimes/kusama.rs), update the  `polkadex_metadata.scale` in the module and import the module in the other project dependency files so you can test it.

I'm happy to review any PR. 

Otherwise let me if there is any test faucet for polkadex so i can test it against their test network.
